### ISSUE TITLE
Issue with starting test server

### ISSUE THREAD

**Issue by finkton1** [polpoy/colyseus-construct-plugin#2]
Hello

When I go to run "npm start" on the test server I get this error message
`C:\Users\Brandon\colyseus-construct-plugin\test\server>npm start

> server-colyseus@1.0.0 start C:\Users\Brandon\colyseus-construct-plugin\test\server
> DEBUG=* ./node_modules/.bin/supervisor -i node_modules -- index.js

'DEBUG' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server-colyseus@1.0.0 start: `DEBUG=* ./node_modules/.bin/supervisor -i node_modules -- index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server-colyseus@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Brandon\AppData\Roaming\npm-cache\_logs\2017-05-30T20_36_12_119Z-debug.log`

Would you know why I may be getting this?

**Comment by endel** [comment]
Hey @finkton1, 

I've just created a pull-request that fixes this issue. https://github.com/polpoy/colyseus-construct-plugin/pull/3/files

Windows don't support setting environment variables like `DEBUG=*` directly. You can also remove the environment variable completely if you aren't interested in the debug information.

**Comment by finkton1** [comment]
Thank you @endel 

When I remove the environment variable it is still throwing me this error:

`Error: Cannot find module 'colyseus'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Brandon\colyseus-construct-plugin\test\server\index.js:3:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
Program node index.js exited with code 1`

**Comment by endel** [comment]
hey @finkton1, you're probably missing to run `npm install` first.

**Comment by fzrasu** [comment]
Thank you for the reference @endel, my test server is on linux openshift server. and i had launched "npm install supervisor" but the server can't get started. i also had tried it on my windows, despite the warnings, it worked well, however, on the openshift  server, it didn't work

**Comment by lgugl** [comment]
Supervisor is just an autorestarter tool to debug quickly. Instead you can launch the index.js file directly with node ("node index"). You can change too all the log.xxx with simple console.log to avoid to use DEBUG= and all the dev dependencies.
