### ISSUE TITLE
Issue with syncing objects

### ISSUE THREAD

**Issue by Poea** [polpoy/colyseus-construct-plugin#4]
![Update](http://i.imgur.com/6eZ1DhP.png)
![Update2](http://i.imgur.com/Kdc6yKk.png)
Cant sync the player objects position even when it's sent via the send to room event

**Comment by lgugl** [comment]
The Send action must simply send a text message to the server. Does your server get the message correctly?

**Comment by Poea** [comment]
@polpoy  Yes the server receives the data correctly but the data doesn't persist, So, I can't have 2 players in a room and visually show them with updated positions, According to endel it's because the room state doesn't save any data due to how the room handler is set up
![rep](http://i.imgur.com/VEqauy3.png)

**Comment by lgugl** [comment]
Where the data doesn't persist? 
Update the state on server side triggers the room update event on client side, with the new room's state. I upload a [small example](https://github.com/polpoy/colyseus-construct-plugin-example).

**Comment by Poea** [comment]
@polpoy  Thank you
