### ISSUE TITLE
any construct 2 example ?

### ISSUE THREAD

**Issue by matrixreal** [polpoy/colyseus-construct-plugin#5]
Hi,
i would like to know if there is a construct 2 example
thank you

**Comment by lgugl** [comment]
Hi,
There is a very simple example in the repo (test/c2test).
I created a more sophisticated [small example](https://github.com/polpoy/colyseus-construct-plugin-example). Maybe I will update it with some comments if it's unclear or buggy. It's not very secure if you want to avoid cheat. A best practice is to send only input and calculate new positions on server side.
