### ISSUE TITLE
i can't start the server, got errors

### ISSUE THREAD

**Issue by fzrasu** [polpoy/colyseus-construct-plugin#6]
Hi Loïc Guglielmino, i loved your multiplayer plugin, however i had problem starting the server, i got errors as bellow. i know little about node js, can you help please? 
My node version is 8.1.0
`
*****.rhcloud.com server]\> npm start

> server-colyseus@1.0.0 start /var/lib/openshift/5*********00010/app-root/runtime/repo/server
> cross-env DEBUG= ./node_modules/.bin/supervisor -i node_modules -- index.js

sh: cross-env: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! server-colyseus@1.0.0 start: `cross-env DEBUG= ./node_modules/.bin/supervisor -i node_modules -- index.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the server-colyseus@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/openshift/5*********00010/app-root/data/.nodejs/.npm/_logs/2017-06-11T08_49_47_158Z-debug.log
`

**Comment by endel** [comment]
https://github.com/polpoy/colyseus-construct-plugin/issues/2#issuecomment-305098923
